### PR TITLE
Correct grammar for switches

### PR DESCRIPTION
**Pull request by poggingfish**
Old:
1 Member fronting:
Switch registered. Current fronter is now Person.
2 Members fronting:
Switch registered. Current fronter is now Person, Person2.

New:
1 Member fronting:
Switch registered. Current fronter is now Person.
2 Members fronting:
Switch registered. Current fronters are now Person, Person2.

### CODE REVIEW

**Comment by spiralw** [comment]
thanks! this should also be done for the result of the [DoEditCommand method](https://github.com/PluralKit/PluralKit/blob/main/PluralKit.Bot/Commands/Switch.cs#L154)

**Comment by poggingfish** [comment]
That should be done now!

**Comment by spiralw** [comment]
sweet. if you fix the failing `dotnet-format` check I can merge this

**Comment by poggingfish** [comment]
Visual studio kept adding the newline at the end back.. i have no idea why. But it should be working just fine now!

**Pull request merged**
